language: node_js
node_js:
  - "6"
  - "5"
  - "4"
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y mecab mecab-ipadic libmecab-dev
script:
  - export CXX=g++-4.8
